# Generated by Django 5.0.6 on 2025-04-03 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_paymentmethod_user_and_more'),
        ('products', '0004_remove_product_color_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='address',
            field=models.TextField(blank=True, default='Unkown', null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(blank=True, default='Unkown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash ', 'Cash on Delivery'), ('credit-card', 'Credit Card'), ('upi', 'UPI')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.cart')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryaddress')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
