# Generated by Django 5.0.6 on 2025-04-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_full_name_deliveryaddress_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
