# Generated by Django 5.0.6 on 2025-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chceckout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chceckout',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
