# Generated by Django 5.0.6 on 2025-04-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_token',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
