# Generated by Django 5.0.6 on 2025-04-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_delete_yourorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chceckout',
        ),
    ]
