# Generated by Django 5.0.6 on 2025-04-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
    ]
