# Generated by Django 5.0.6 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_razorpaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='contact_number',
            field=models.CharField(blank=True, default='Unkown', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
