# Generated by Django 5.0.6 on 2024-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='static/colorvariant'),
            preserve_default='True',
        ),
    ]
