# Generated by Django 5.0.6 on 2024-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fake_price',
            field=models.IntegerField(default=0),
        ),
    ]
