# Generated by Django 5.0.6 on 2025-03-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_paymentmethod_user_and_more'),
        ('products', '0003_product_fake_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.DeleteModel(
            name='colorvariant',
        ),
        migrations.DeleteModel(
            name='sizevariant',
        ),
    ]
