# Generated by Django 5.0.6 on 2025-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productsimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productsimage',
            name='updated_at',
        ),
    ]
