# Generated by Django 5.0.6 on 2025-04-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
