# Generated by Django 5.0.6 on 2025-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fake_price',
        ),
    ]
